dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure: YcT6d+2EB5hBnP+YylQyjhaUat0hhMTCotU8SEE5cneESmgXLzHlhB1EvGyoNo6ORvzW9yMnEzc58wmfvmtNRaZfecv3EMFuNtrIOSRQlpVvymNG3N8gr4fk+EwC4eaayAeR+fmndFU+CaAaQHumlFzGHcSMGXElDH+yIJnOnMbvldlTI3PS3pd3EqsGlVUBa66X7MV373qNpkYJV00tDCU4qwbupBcnGmdi1TCRSbaCKVcma++XCqpJNrdQgGmd8dCQkZXPE6p5Z4dJd+I9itdGnl11xRdfPkfXH5v752EB4hwxjHPLJlwbcILSkwJbKPW8GoKtf6NXj6+hs0Ea/XfqjD2pa2zQQUDaBe96UDxblpjN8DUfgq0fdtkLMMewZJnVZYgDh+PWC3ctPmYkUgW+eWpzAi8zUYkoGa9fW47/mT0Ndb0aModDJEQotBCvZ2WGP0/K6jJEVJUpoaN5d2i/hK36XseF/eE3Fvxj+NyCbZlflEAJFqC2iB6ZAzYd4PhA26LneBtLgod8gy56vWRrbUWNAFlfZLDkN5WZMCSwsd3BZ95bB7q/yy9DSPjmECHZNnLwmycnNmEc9vwbWVo1x6w3PzsdC72lvEmam63VEh03vH9jC9mFzyPhCsEeE6xdGQ0JjSTX9KYLxW16RzkKzqwKEmARLD4XuLtggN0=
